[project]
name = "Context-Engineering-with-DSPy"
version = "0.1.0"
description = "Context-Engineering with DSPy"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.31.0",
    "ipykernel>=6.30.1",
    "openai>=1.101.0",
    "python-dotenv>=1.1.1",
]
